# Generated by Django 5.2 on 2025-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activation_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
