# Generated by Django 5.2 on 2025-05-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activationemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationemaillog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationemaillog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
