# Generated by Django 5.2 on 2025-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activationemaillog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
