# Generated by Django 5.2 on 2025-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_blocked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_permanently_banned',
            field=models.BooleanField(default=False),
        ),
    ]
